#' GPT-2 Samples
#'
#' This package contains all sample data as generated by OpenAI's GPT-2 language model.
#' The data includes conditional texts with sample prompts and their completions, as well as
#' the unconditional texts with samples of generated text.
#' @docType package
#' @name gpt2samples
#' @aliases gpt2samples gpt2samples-package
NULL

#' @title Conditional with temperature 0.7
#' @description Conditionally generated texts with contexts from WebText's test set
#' @format A data frame with 1000 rows and 4 variables:
#' \describe{
#'   \item{\code{file}}{character file reference}
#'   \item{\code{id}}{integer sample and completion id number in the file}
#'   \item{\code{text}}{character the text, either a sample context or a completion}
#'   \item{\code{type}}{character indicator of whether the text is a sample context or a completion}
#'}
#' @source \url{https://github.com/openai/gpt-2/tree/master/gpt-2-samples}
"conditional_t07"

#' @title Conditional with truncation 1 with top_40 k
#' @description Conditionally generated texts with contexts from WebText's test set
#' @format A data frame with 1000 rows and 4 variables:
#' \describe{
#'   \item{\code{file}}{character file reference}
#'   \item{\code{id}}{integer sample and completion id number in the file}
#'   \item{\code{text}}{character the text, either a sample context or a completion}
#'   \item{\code{type}}{character indicator of whether the text is a sample context or a completion}
#'}
#' @source \url{https://github.com/openai/gpt-2/tree/master/gpt-2-samples}
"conditional_topk40"

#' @title Conditional with default settings
#' @description Conditionally generated texts with contexts from WebText's test set
#' @format A data frame with 1000 rows and 4 variables:
#' \describe{
#'   \item{\code{file}}{character file reference}
#'   \item{\code{id}}{integer sample and completion id number in the file}
#'   \item{\code{text}}{character the text, either a sample context or a completion}
#'   \item{\code{type}}{character indicator of whether the text is a sample context or a completion}
#'}
#' @source \url{https://github.com/openai/gpt-2/tree/master/gpt-2-samples}
"conditional"
